import { writeSafeFile } from '../utils/fsx.js';
import { uuid, semverBump } from '../utils/ids.js';
import { writeSoloHostPackage } from './solohost.js';

export class ReleaseManager {
  constructor({ cfg, db, log }) {
    this.cfg = cfg;
    this.db = db;
    this.log = log;
  }

  list(projectId) {
    return this.db.all('SELECT * FROM releases WHERE project_id = ? ORDER BY created_at DESC', projectId);
  }

  async prepareNotes(project, sourceDir, quality) {
    const version = project.version || '0.1.0';
    const notes = `# ${project.name} ${version}

Generated by App Builder — Pi SoloHost.

## What it does
${project.idea || project.name}

## Quality
${quality ? JSON.stringify(quality, null, 2) : 'See project checks.'}

## Install
Read INSTALL.md in the project folder.
`;
    await writeSafeFile(sourceDir, 'RELEASE_NOTES.md', notes);
    await writeSafeFile(sourceDir, 'CHANGELOG.md', `## ${version}\n\n- Initial release generated from your idea.\n`);
    return { version, notes };
  }

  async validateSoloHost(sourceDir) {
    try {
      const fs = await import('node:fs/promises');
      const path = await import('node:path');
      const compose = await fs.readFile(path.join(sourceDir, 'solohost', 'docker-compose.yml'), 'utf8');
      const config = await fs.readFile(path.join(sourceDir, 'solohost', 'config_options.yml'), 'utf8');
      if (!compose.includes('image:') || !config.includes('title:')) {
        return { ok: false, errors: ['SoloHost files are incomplete.'] };
      }
      const res = await fetch('https://solohost-nohcqud24xwnsmna.staging.piappengine.com/api/apps/validate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ composeYaml: compose, configOptionsYaml: config }) });
      const data = await res.json().catch(() => ({}));
      if (!res.ok || data.ok !== true) return { ok: false, errors: Array.isArray(data.errors) ? data.errors : [`SoloHost validator returned HTTP ${res.status}.`] , authoritative: true };
      return { ok: true, errors: [], authoritative: true };
    } catch (err) {
      return { ok: false, errors: [String(err.message || err)] };
    }
  }

  async prepareSoloHost(project, sourceDir, image, description = '') {
    const hostPort = 18080 + Math.floor(Math.random() * 200);
    return writeSoloHostPackage({ project, sourceDir, image, hostPort, description });
  }

  record(project, { version, notes, githubUrl, status = 'created' }) {
    const id = uuid();
    this.db.run(
      `INSERT INTO releases(id,project_id,version,notes,github_url,status,created_at)
       VALUES(?,?,?,?,?,?,?)`,
      id, project.id, version, notes, githubUrl || null, status, new Date().toISOString(),
    );
    return this.db.get('SELECT * FROM releases WHERE id = ?', id);
  }

  nextVersion(project, kind = 'patch') {
    return semverBump(project.version || '0.1.0', kind);
  }
}
